# Site settings
title: Daniel Crown
email: crown.17@osu.edu
description: > # this means to ignore newlines until "baseurl:"
  I am a PhD Candidate in the AEDE department at The Ohio State University.  My research interests include immigration and applied microeconomics. 
# baseurl: "/" # the subpath of your site, e.g. /blog/

github_username:  daniel-crown
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
